### ISSUE TITLE
Feat: define color scheme in toml

### ISSUE THREAD

**Issue by olivercederborg** [olivercederborg/poimandres-wezterm#2]

**Comment by wez** [comment]
I came here to say: please provide a TOML file. It's safer for users and I can then sync it into wezterm for the next release!

See: https://github.com/Hiroya-W/wezterm-sequoia-theme/issues/1
and: https://github.com/EdenEast/nightfox.nvim/issues/183

**Comment by olivercederborg** [comment]
> I came here to say: please provide a TOML file. It's safer for users and I can then sync it into wezterm for the next release!
> 
> 
> 
> See: https://github.com/Hiroya-W/wezterm-sequoia-theme/issues/1
> 
> and: https://github.com/EdenEast/nightfox.nvim/issues/183

Thank you Wez - will get this done ASAP!

**Comment by wez** [comment]
Thanks! BTW, https://github.com/EdenEast/nightfox.nvim/issues/183#issuecomment-1189655306 shows how you can fairly easily export the lua file to toml using a built-in function

**Comment by olivercederborg** [comment]
> Thanks! BTW, https://github.com/EdenEast/nightfox.nvim/issues/183#issuecomment-1189655306 shows how you can fairly easily export the lua file to toml using a built-in function

Amazing 🙌

**Comment by olivercederborg** [comment]
@wez The current two versions of the theme have now been converted to toml and are located in `/dist` 

Edit: I have moved the contents of this repo to https://github.com/olivercederborg/poimandres.nvim/tree/main/extra/wezterm to keep everything contained

**Comment by wez** [comment]
Thanks! Sync'd and now visible at:
https://wezfurlong.org/wezterm/colorschemes/p/index.html#poimandres
https://wezfurlong.org/wezterm/colorschemes/p/index.html#poimandres-storm
